### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by prjctimg**
@adarshswaminath @takanome-dev  What do you think about the current state of our docs. Please check out the new `guides/` directory. I was hoping adding quick introductory material on color theory will make this project easier to use.

### CODE REVIEW

**Comment by adarshswaminath** [comment]
@prjctimg I think it gets better when sample code is added

**Comment by prjctimg** [comment]
> @prjctimg I think it gets better when sample code is added

@adarshswaminath Great observation!

The sample code will simply be from our (beta) docs. Would you have any idea on how we can automate our documentation generation? 

Are you able to work on the README to add missing code samples (if any) and fill in the empty links ?

**Comment by adarshswaminath** [comment]
@prjctimg I appreciate the opportunity, but currently, I'm unable to work on it due to my ongoing university exams. I hope you understand

**Comment by prjctimg** [comment]
> @prjctimg I appreciate the opportunity, but currently, I'm unable to work on it due to my ongoing university exams. I hope you understand

No worries at all! All the best!

**Pull request merged**
