### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by prjctimg**
Fixed broken link to the docs.

Now that I think of it, our README is boring and leaves a lot of information gaps. Let's give it a rewrite!

### CODE REVIEW

**Review by adarshswaminath — APPROVED** [review]
Ok

**Review by adarshswaminath — APPROVED** [review]
Ok

**Review by Cubic-ctrl — APPROVED** [review]
Ok. Might also add some quick entry points into the library.

**Review by adarshswaminath — APPROVED** [review]
👍 **Code Review Approved with a Suggestion** 👍

Great work on this README! You've provided a clear and informative introduction to the project, highlighting its purpose, features, and potential use cases.

Your explanations are concise and to the point, making it easy for readers to grasp the project's value quickly.

 I recommend adding code examples to illustrate how the library can be used. These examples will provide practical guidance for developers and designers who want to leverage your library in their projects. You can include code snippets for common use cases to make it even more user-friendly.

Overall, excellent work on the README, and I'm looking forward to seeing how this project evolves!

If you have any questions or need further feedback on the code or any other aspects of the project, feel free to reach out.

Keep up the great work! 🚀

**Pull request closed without merging**
