### PR TITLE
chore: add release cycle

### LINKED ISSUE #92: Chore: add release cycle
I've noticed that the project doesn't release often enough to stay afloat in terms of traffic on both GitHub and NPM. To improve our outreach, how can we maintain a development pace that allows us to release patches or updates to the library at least once a week. This observation was inspired by open-sauced which mantains a very active release cycle. 

Ideas and suggestions for workflow management are greatly welcome! 

Let's make this project active and thriving! 🚀

_Originally posted by @prjctimg in https://github.com/prjctimg/huetiful/discussions/86_

### PR DESCRIPTION
**Pull request by takanome-dev**
## Description

This PR adds a `release` workflow which builds the project by using the `development` workflow file, then releases the project and finally deploys to Vercel.

I'm not 100% sure that this is going to work well as I didn't try it and was given the code. We will need to just try it and figure out how to fix issues as we encounter them.

## Related Tickets

Fixes #92

### CODE REVIEW

**Comment by takanome-dev** [comment]
@prjctimg you will need to add Vercel tokens in the action configs:
- `VERCEL_ORG_ID`
- `VERCEL_PROJECT_ID`
- `VERCEL_TOKEN`

You also need to switch Vercel deployment from auto to the CLI

**Review by prjctimg — CHANGES_REQUESTED** [review]
This looks awesome! 🚀 Thank you for the changes! 

So this workflow which requires VERCEL credentials is for the docs site right? 

Which means the workflow file will need to leave on the documentation repository? 

Setting up the required fields asap !

**Review by prjctimg — CHANGES_REQUESTED** [review]
This looks awesome! 🚀 Thank you for the changes! 

So this workflow which requires VERCEL credentials is for the docs site right? 

Which means the workflow file will need to leave on the documentation repository? 

Setting up the required fields asap !

**Comment by takanome-dev** [comment]
> So this workflow which requires VERCEL credentials is for the docs site right?

Yes
> Which means the workflow file will need to leave on the documentation repository?

Oh my bad, I thought the docs were left in this repo :sweat_smile: 
I need to remove the deploy task and move it to the docs then. Nice catch :+1:

**Comment by prjctimg** [comment]
> > So this workflow which requires VERCEL credentials is for the docs site right?
> 
> Yes
> > Which means the workflow file will need to leave on the documentation repository?
> 
> Oh my bad, I thought the docs were left in this repo :sweat_smile: 
> I need to remove the deploy task and move it to the docs then. Nice catch :+1: 

@takanome-dev I sent you a collaboration request from the docs repository. Feel free to make necessary changes 👍

**Pull request closed without merging**
